name: flutter_ai_quant
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Responsive Layout
  device_preview: ^0.5.5
  responsive_widgets: ^2.0.1

  # Management State
  provider: ^5.0.0
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3

  # Management Route
  fluro: ^2.0.3

  # Call API, Parse JSON
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  json_serializable: ^4.0.2

  # Local Database
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  hive_generator: ^1.0.0

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/gai1.jpg
    - assets/logo_transparent.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
